### PR TITLE
noob-friendly content editor

### PR DESCRIPTION
**Pull request by ineeee**
i've added the homepage script as an example -- the user has to be simply logged in and everything else is handled by javascript

edit: uploaded example http://inex.ga/home/Categories-Anon/

### CODE REVIEW

**Comment by 0XE4** [comment]
Thanks @inexist3nce but would it be possible to create a homepage and then link your script into it? Or duplicate an existing one? I'd rather not change existing startpages in order to conserve them 'as is'.

**Comment by ineeee** [comment]
(I think I didn't understand?) All the script does is replace the existing contents with the user's, it doesn't need to be tightly integrated into the homepage's code. In the example, I simply added the script and a function to create the html, trying to not invade the code too much.

**Comment by 0XE4** [comment]
I'll duplicate that page and then write a description linking to your database @inexist3nce

**Comment by 0XE4** [comment]
Added your edited page into the startpage list with a link back to you @inexist3nce

**Comment by ineeee** [comment]
Thanks :D

**Pull request closed without merging**
